/* eslint-disable */

// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

 

const awsmobile = {

    "aws_project_region": "us-east-1",

    "aws_cognito_identity_pool_id": "us-east-1:552392a6-0663-4301-a219-645e1254f489",

    "aws_cognito_region": "us-east-1",

    "aws_user_pools_id": "us-east-1_P5U9oHBkz",

    "aws_user_pools_web_client_id": "5iife0ui6fdb2avb0r7t6lg3st",

    "oauth": {},

    "aws_cognito_username_attributes": [

        "EMAIL",

        "PHONE_NUMBER"

    ],

    "aws_cognito_social_providers": [],

    "aws_cognito_signup_attributes": [

        "EMAIL"

    ],

    "aws_cognito_mfa_configuration": "OFF",

    "aws_cognito_mfa_types": [

        "SMS"

    ],

    "aws_cognito_password_protection_settings": {

        "passwordPolicyMinLength": 8,

        "passwordPolicyCharacters": []

    },

    "aws_cognito_verification_mechanisms": [

        "EMAIL"

    ]

};

 

 

export default awsmobile;

 